# Generated by Django 5.2.17 on 2026-10-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
    ]
