# Generated by Django 5.2.17 on 2026-10-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
