# Generated by Django 5.2.17 on 2026-10-09 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_role_auditlog'),
        ('transactions', '0002_transaction_failure_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(db_index=True)),
                ('response_time_ms', models.FloatField()),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FraudLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('rule_triggered', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('location', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('device_info', models.CharField(blank=True, default='Web', max_length=255, null=True)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('CONFIRMED', 'Confirmed Fraud'), ('FALSE_POSITIVE', 'False Positive'), ('RESOLVED', 'Resolved')], default='UNDER_REVIEW', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Shopping', 'Shopping'), ('Dining', 'Dining'), ('Utilities', 'Utilities'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('General', 'General')], db_index=True, default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device_info',
            field=models.CharField(blank=True, default='Web', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fraud_status',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('SUSPICIOUS', 'Suspicious'), ('FLAGGED', 'Flagged'), ('BLOCKED', 'Blocked')], db_index=True, default='CLEAN', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-transaction_date'], name='transaction_user_id_64ff44_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-transaction_date'], name='transaction_status_5f6953_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', '-transaction_date'], name='transaction_categor_42ab49_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fraud_status'], name='transaction_fraud_s_6144fd_idx'),
        ),
        migrations.AddField(
            model_name='apimetriclog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_metric_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudlog',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_logs', to='accounts.card'),
        ),
        migrations.AddField(
            model_name='fraudlog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudlog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_logs', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='fraudlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
